### ISSUE TITLE
🛑 Ion is down

### ISSUE THREAD

**Issue by tjhsst-ion** [tjcsl/status#1]
In [`52db6a0`](https://github.com/tjcsl/status/commit/52db6a0b000d54d4aa47037fb58742bdfc0c70be
), Ion (https://ion.tjhsst.edu) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by etnguyen03** [comment]
**Monitoring**: A fix has been implemented and we are monitoring the results.
